import { Instagram, Mail, MapPin, Phone } from 'lucide-react';
import { phoneHref } from '@/lib/utils/contact';
import type { SiteSettings } from '@/types/database';
import AcademyLogo from './AcademyLogo';

export default function SiteFooter({ settings }: { settings: SiteSettings }) {
  return (
    <footer className="relative border-t border-white/5 bg-[#0A0A0A] py-16"><div className="mx-auto max-w-6xl px-6"><div className="mb-10 grid grid-cols-1 gap-10 md:grid-cols-3"><div><AcademyLogo variant="light" className="mb-5 h-20 w-auto" /><p className="text-sm leading-relaxed text-white/40">Juventus FC resmi ortaklığıyla, Batıkent&apos;te dünya standartlarında futbol eğitimi. İtalyan disiplini ve metodolojisi ile geleceğin yıldızlarını yetiştiriyoruz.</p></div><div><h4 className="mb-4 text-sm font-semibold uppercase tracking-wider text-white">Hızlı Linkler</h4><ul className="space-y-2 text-sm text-white/40"><li><a href="#programlar" className="hover:text-white">Programlar</a></li><li><a href="#galeri" className="hover:text-white">Galeri</a></li><li><a href="#sosyal-medya" className="hover:text-white">Sosyal Medya</a></li><li><a href="#kayit" className="hover:text-white">Kayıt</a></li><li><a href="#konum" className="hover:text-white">İletişim</a></li></ul></div><div><h4 className="mb-4 text-sm font-semibold uppercase tracking-wider text-white">İletişim</h4><div className="space-y-3 text-sm text-white/50"><p className="flex items-start gap-2"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-amber-400" />{settings.address}</p><a href={phoneHref(settings.phone_primary)} className="flex items-center gap-2 hover:text-white"><Phone className="h-4 w-4 text-amber-400" />{settings.phone_primary}</a>{settings.phone_secondary ? <a href={phoneHref(settings.phone_secondary)} className="flex items-center gap-2 hover:text-white"><Phone className="h-4 w-4 text-amber-400" />{settings.phone_secondary}</a> : null}<a href={`mailto:${settings.email}`} className="flex items-center gap-2 break-all hover:text-white"><Mail className="h-4 w-4 shrink-0 text-amber-400" />{settings.email}</a>{settings.instagram_enabled && settings.instagram_url ? <a href={settings.instagram_url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 font-semibold text-amber-300 hover:text-amber-200"><Instagram className="h-4 w-4" />@{settings.instagram_username.replace(/^@/, '')}</a> : null}</div></div></div><div className="flex flex-col items-center justify-between gap-4 border-t border-white/5 pt-6 md:flex-row"><p className="text-xs text-white/20">Juventus FC tescilli markası ve logosu, Juventus Football Club S.p.A.&apos;nın mülkiyetindedir.</p><p className="text-xs text-white/30">© {new Date().getFullYear()} {settings.academy_name}. Tüm hakları saklıdır.</p></div></div></footer>
  );
}
