import { ExternalLink, MapPin, MessageCircle, Navigation, Phone } from 'lucide-react';
import { phoneHref, whatsappHref } from '@/lib/utils/contact';
import { isSafeGoogleMapsUrl } from '@/lib/utils/maps';
import type { SiteSettings } from '@/types/database';

export default function VisitSection({ settings }: { settings: SiteSettings }) {
  const safeEmbed = settings.map_enabled && isSafeGoogleMapsUrl(settings.google_maps_embed_url, false);
  const safeDirections = isSafeGoogleMapsUrl(settings.google_maps_directions_url, false);
  return (
    <section id="konum" className="relative scroll-mt-20 border-t border-white/5 bg-[#050505] py-20 md:py-28"><div className="mx-auto max-w-6xl px-6"><div className="mb-10"><p className="mb-3 text-xs font-bold uppercase tracking-[0.28em] text-amber-400">Konum ve İletişim</p><h2 className="text-3xl font-black md:text-5xl">Bizi Ziyaret Edin</h2></div><div className={`grid overflow-hidden rounded-3xl border border-white/10 bg-[#0A0A0A] ${safeEmbed ? 'lg:grid-cols-[0.9fr_1.1fr]' : ''}`}><div className="p-7 md:p-10"><MapPin className="mb-6 h-8 w-8 text-amber-400" /><h3 className="mb-2 text-2xl font-black">{settings.venue_name}</h3><p className="mb-8 max-w-lg leading-relaxed text-white/45">{settings.address}</p><div className="flex flex-wrap gap-3">{safeDirections ? <><a href={settings.google_maps_directions_url} target="_blank" rel="noopener noreferrer" className="contact-button bg-amber-400 text-black hover:bg-amber-300"><Navigation className="h-4 w-4" /> Yol Tarifi Al</a><a href={settings.google_maps_directions_url} target="_blank" rel="noopener noreferrer" className="contact-button border border-white/15 text-white hover:border-amber-400/40"><ExternalLink className="h-4 w-4" /> Google Maps&apos;te Aç</a></> : null}<a href={phoneHref(settings.phone_primary)} className="contact-button border border-white/15 text-white hover:border-amber-400/40"><Phone className="h-4 w-4" /> Telefonla Ara</a>{settings.whatsapp_enabled ? <a href={whatsappHref(settings.whatsapp_number, settings.whatsapp_message)} target="_blank" rel="noopener noreferrer" className="contact-button border border-emerald-500/30 text-emerald-300 hover:bg-emerald-500/10"><MessageCircle className="h-4 w-4" /> WhatsApp&apos;tan Ulaş</a> : null}</div></div>{safeEmbed ? <div className="relative min-h-[340px] border-t border-white/10 lg:border-l lg:border-t-0"><iframe src={settings.google_maps_embed_url} title={`${settings.venue_name} Google Maps konumu`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="absolute inset-0 h-full w-full border-0" allowFullScreen /></div> : null}</div></div></section>
  );
}
